[package]
name = "werk-parser"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[[test]]
name = "test_errors"
src = "tests/test_errors.rs"

[dependencies]
indexmap.workspace = true
toml_edit.workspace = true
thiserror.workspace = true
unicode-ident = "1.0.13"
winnow.workspace = true
regex.workspace = true
annotate-snippets = "0.11.5"

[dev-dependencies]
anstream = "0.6.18"

[lints]
workspace = true
